### ISSUE TITLE
Not working on M1 Big Sur new laptop?

### ISSUE THREAD

**Issue by Infrabass** [GimmyHchs/alfred-workflow-bitly#4] opened 2021-06-24 19:01 UTC
The workflow was working perfectly on OSX 10.10.5 but on Big Sur it seems to be broken.
Has this been reported compatible with this OS?

**Comment by GimmyHchs** [comment] 2021-06-28 02:30
> The workflow was working perfectly on OSX 10.10.5 but on Big Sur it seems to be broken.
> Has this been reported compatible with this OS?

This workflow hasn't been test on new macbook.
Maybe `M1 Chip` is the root cause?
I'm not sure. I don't have M1 chip macbook.

My test environment
```
MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)
Intel Core i5
```

The workflow works well.

https://bit.ly/3xUeeGU

**Comment by Infrabass** [comment] 2021-06-28 20:37
I'm using a new M1 MacBook air indeed.
I hope this awesome workflow can be updated to work with the new Apple chip.

**Comment by GimmyHchs** [comment] 2021-06-30 02:14
@Infrabass I've try on M1 macbook pro. I can shorten the URL `without any error`.

Can you provide your `error log (Alfred debug message)` ?

Here is the way to get log in debug mode:
![CleanShot 2021-06-30 at 10 08 43](https://user-images.githubusercontent.com/11835351/123891383-6c902680-d98b-11eb-8c87-8cf81f573ba1.png)

Enable the debug mode and try to `shorten URL again`. You can get the log message. Thx.

**Comment by GimmyHchs** [comment] 2021-07-07 07:04
@Infrabass any update?

**Comment by Infrabass** [comment] 2021-07-09 03:20
Hi Gimmy,

Sorry for my late reply, I was undersea with work.

It seems I made an error while installing jq, the command is not found.



I remember the process wasn’t that easy.

Actually I just tried to re-install jq and it says it’s already installed.





Strange.

Thanks for the help and sorry for reporting an incorrect issue.


Vincent F.

**Comment by GimmyHchs** [comment] 2021-07-13 02:32
> Hi Gimmy, Sorry for my late reply, I was undersea with work. It seems I made an error while installing jq, the command is not found. I remember the process wasn’t that easy. Actually I just tried to re-install jq and it says it’s already installed. Strange. Thanks for the help and sorry for reporting an incorrect issue. Vincent F.
> […](#)

Do you set the JQPATH correctly?

https://github.com/GimmyHchs/alfred-workflow-bitly#installation

You can get the JQPATH via which command.

```
$ which jq
```

**Comment by Infrabass** [comment] 2021-07-16 17:10
That’s it, the path was incorrect!
In fact, the command $ which jq wasn’t working.
I needed to use which jq instead.
Thanks again,
Take care.

Vincent Fliniaux
FREELANCE SOUND ARTIST
Sound Designer, Field Recordist, Location Sound & Post-Production
+1 (438) 829-2410
http://www.vincentfliniaux.com
https://bruits.studio

**Comment by GimmyHchs** [comment] 2021-07-19 03:18
Thanks for ur report!

Close the issue.

**Closed as completed by GimmyHchs** 2021-07-19 03:18 UTC
Labels: question
